config/routes.rb
Rails.application.routes.draw do


  get 'users/:id', to:'userinfos#show',as: 'user_detail'

  #article-icon-bar
  post 'bookmarks/create'
  delete 'bookmarks/destroy'
  post 'unlike_articles/create'
  delete 'unlike_articles/destroy'
  post 'like_articles/create'
  delete 'like_articles/destroy'



  get 'categories/:id', to:'categories#show',as: 'show_category'


  resources :articles

  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :title,:user_id,:content,:category_id,presence:true
  validates :title,length:{minimum:1,maximum:20}
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id,:article_id,presence:true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
  validates :name,presence: true
end

app/models/like_article.rb
class LikeArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id,:article_id,presence:true
end

app/models/unlike_article.rb
class UnlikeArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id,:article_id,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  protected

  def email_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
    @article=Article.find(params[:id])
  end

  def create
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    Bookmark.create(user_id:params[:user],article_id:params[:article])
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article}
      format.js   { render "article_icon/refresh" }
      format.json { render json: @article, status: :created, location: @article }
    end
  end

  def destroy
    Bookmark.where(user_id:params[:user],article_id:params[:article]).find_each do |cate|
      cate.destroy
    end
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article }
      format.js   { render "article_icon/refresh" }
      format.json { render json: @article, status: :created, location: @article }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category=Category.find(params[:id])
    if @category.id.to_int<5
      @categories=Category.find([1,2,3,4])
      @title="SHIVA@GUN"
    else
      @categories=Category.find([5,6,7,8])
      @title="SHIVA@FUN"
    end
    @articles=@category.articles.order("created_at DESC")
  end
end

app/controllers/like_articles_controller.rb
class LikeArticlesController < ApplicationController
  def create
    LikeArticle.create(user_id:params[:user],article_id:params[:article])
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article}
      format.js   {}
      format.json { render json: @article, status: :created, location: @article }
    end
  end

  def destroy
    LikeArticle.where(user_id:params[:user],article_id:params[:article]).find_each do |cate|
      cate.destroy
    end
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article }
      format.js   {}
      format.json { render json: @article, status: :created, location: @article }
    end
  end
end

app/controllers/unlike_articles_controller.rb
class UnlikeArticlesController < ApplicationController
  def create
    UnlikeArticle.create(user_id:params[:user],article_id:params[:article])
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article}
      format.js   { render "article_icon/refresh" }
      format.json { render json: @article, status: :created, location: @article }
    end
  end

  def destroy
    UnlikeArticle.where(user_id:params[:user],article_id:params[:article]).find_each do |cate|
      cate.destroy
    end
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article }
      format.js   { render "article_icon/refresh" }
      format.json { render json: @article, status: :created, location: @article }
    end
  end
end

app/controllers/userinfos_controller.rb
class UserinfosController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tt=1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/like_articles_helper.rb
module LikeArticlesHelper
end

app/helpers/unlike_articles_helper.rb
module UnlikeArticlesHelper
end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<% arclass="panel panel-default ar"+article.id.to_s %>
<div class="<%= arclass %>">
  <h2><%= article.title %></h2>
  <p class="article-author">by
    <%= link_to article.user.username, "#" %>
    <%= "      "+DateTime.parse(article.created_at.to_s).strftime('%Y-%m-%d %H:%M:%S').to_s %>
  </p>
  <hr>
  <p class="article-content">
    <%= article.content %>
  </p>
  <hr>
  <div class="article-icon">
    <i class="fa fa-eye fa-lg"></i>
    <i class="icon-des">12</i>
    <% if current_user %>
        <% if LikeArticle.where(user_id: current_user.id, article_id: article.id).first==nil %>
            <%= link_to (content_tag :li, "", class: "fa fa-thumbs-o-up fa-lg"), like_articles_create_path(:user => current_user.id, :article => article.id), method: "post", remote: true %>
        <% else %>
            <%= link_to (content_tag :li, "", class: "fa fa-thumbs-up fa-lg"), like_articles_destroy_path(:user => current_user.id, :article => article.id), method: "delete", remote: true %>
        <% end %>
        <i class="icon-des"><%= LikeArticle.where(article_id:article.id).count %></i>
        <% if UnlikeArticle.where(user_id: current_user.id, article_id: article.id).first==nil %>
            <%= link_to (content_tag :li, "", class: "fa fa-thumbs-o-down fa-lg"), unlike_articles_create_path(:user => current_user.id, :article => article.id), method: "post", remote: true %>
        <% else %>
            <%= link_to (content_tag :li, "", class: "fa fa-thumbs-down fa-lg"), unlike_articles_destroy_path(:user => current_user.id, :article => article.id), method: "delete", remote: true %>
        <% end %>
        <i class="icon-des"><%= UnlikeArticle.where(article_id:article.id).count %></i>
        <% if Bookmark.where(user_id: current_user.id, article_id: article.id).first==nil %>
            <%= link_to (content_tag :li, "", class: "fa fa-bookmark-o fa-lg"), bookmarks_create_path(:user => current_user.id, :article => article.id), method: "post", remote: true %>
        <% else %>
            <%= link_to (content_tag :li, "", class: "fa fa-bookmark fa-lg"), bookmarks_destroy_path(:user => current_user.id, :article => article.id), method: "delete", remote: true %>
        <% end %>
        <i class="icon-des"><%= Bookmark.where(article_id:article.id).count %></i>
    <% else %>
        <i class="fa fa-thumbs-o-up fa-lg"></i>
        <i class="icon-des">12</i>
        <i class="fa fa-thumbs-o-down fa-lg"></i>
        <i class="icon-des">12</i>
        <i class="fa fa-bookmark-o fa-lg"></i>
        <i class="icon-des">12</i>
    <% end %>
    <i class="fa fa-comments fa-lg"></i>
    <i class="icon-des">12</i>
  </div>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>
<%form_for %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<h1>Articles#show<%= @tt %></h1>
<p>Find me in app/views/articles/show.html.erb</p>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.content %>
</p>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/categories/show.html.erb
<% provide(:title, "SHIVA's "+@category.name) %>
<body>
<div id="shangxia2">
				<span id="gotop1">
          <%= image_tag "huojian.svg", :alt => "返回顶部" %>
				</span>
</div>


<div id="paper-back">
  <nav>
    <div class="close"></div>
    <a href="#">主页</a>
    <a href="#">关于本站</a>
    <a href="#">支持</a>
    <a href="#">联系我</a>
  </nav>
</div>
<div id="paper-window">
  <div id="paper-front">
    <%= render "shared/navigator" %>
    <div class="hamburger"><span></span></div>
    <div class="container theme-showcase" role="main">
      <div class="article-button">
        <a href="#" class="button button-glow button-rounded button-primary">最新</a>
        <a href="#" class="button button-glow button-border button-rounded button-primary">最热</a>
        <a href="#" class="button button-glow button-border button-rounded button-primary">最多评论</a>
        <a href="#" class="button button-glow button-rounded button-royal button-pill"><i class="fa fa-pencil"></i>发布</a>
      </div>
      <div class="article-list" id="article-list">
        <%= render @articles %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        // 返回顶部，绑定gotop1图标和gotop2文字事件
        $("#gotop1").click(function (e) {
            TweenMax.to(window, 1.5, {scrollTo: 0, ease: Expo.easeInOut});
            var huojian = new TimelineLite();
            huojian.to("#gotop1", 1, {rotationY: 720, scale: 0.6, y: "+=40", ease: Power4.easeOut})
                .to("#gotop1", 1, {y: -1000, opacity: 0, ease: Power4.easeOut}, 0.6)
                .to("#gotop1", 1, {
                    y: 0,
                    rotationY: 0,
                    opacity: 1,
                    scale: 1,
                    ease: Expo.easeOut,
                    clearProps: "all"
                }, "1.4");
        });

    });
    var paperMenu = {
        $window: $('#paper-window'),
        $paperFront: $('#paper-front'),
        $hamburger: $('.hamburger'),
        offset: 1800,
        pageHeight: $('#paper-front').outerHeight(),
        open: function () {
            this.$window.addClass('tilt');
            this.$hamburger.off('click');
            $('#container, .hamburger').on('click', this.close.bind(this));
            this.hamburgerFix(true);
            // console.log('opening...');
        },
        close: function () {
            this.$window.removeClass('tilt');
            $('#container, .hamburger').off('click');
            this.$hamburger.on('click', this.open.bind(this));
            this.hamburgerFix(false);
            // console.log('closing...');
        },
        updateTransformOrigin: function () {
            scrollTop = this.$window.scrollTop();
            equation = (scrollTop + this.offset) / this.pageHeight * 100;
            this.$paperFront.css('transform-origin', 'center ' + equation + '%');
        },
        hamburgerFix: function (opening) {
            if (opening) {
                $('.hamburger').css({
                    position: 'absolute',
                    top: this.$window.scrollTop() + 30 + 'px'
                });
            } else {
                setTimeout(function () {
                    $('.hamburger').css({
                        position: 'fixed',
                        top: '73px'
                    });
                }, 300);
            }
        },
        bindEvents: function () {
            this.$hamburger.on('click', this.open.bind(this));
            $('.close').on('click', this.close.bind(this));
            this.$window.on('scroll', this.updateTransformOrigin.bind(this));
        },
        init: function () {
            this.bindEvents();
            this.updateTransformOrigin();
        }
    };
    paperMenu.init();
</script>
</body>

app/views/like_articles/create.js.erb
$(".ar<%= @article.id.to_s %>").replaceWith("<%= j(render @article) %>");