config/routes.rb
Rails.application.routes.draw do


  get 'users/:id', to:'userinfos#show',as: 'user_detail'

  #article-icon-bar
  post 'bookmarks/create'
  delete 'bookmarks/destroy'
  post 'unlike_articles/create'
  delete 'unlike_articles/destroy'
  post 'like_articles/create'
  delete 'like_articles/destroy'



  get 'categories/:id', to:'categories#show',as: 'show_category'


  resources :articles

  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :title,:user_id,:content,:category_id,presence:true
  validates :title,length:{minimum:1,maximum:20}
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id,:article_id,presence:true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
  validates :name,presence: true
end

app/models/like_article.rb
class LikeArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id,:article_id,presence:true
end

app/models/unlike_article.rb
class UnlikeArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id,:article_id,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  protected

  def email_required?
    false
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
    @article=Article.find(params[:id])
  end

  def create
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    Bookmark.create(user_id:params[:user],article_id:params[:article])
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article}
      format.js   { render "article_icon/refresh" }
      format.json { render json: @article, status: :created, location: @article }
    end
  end

  def destroy
    Bookmark.where(user_id:params[:user],article_id:params[:article]).find_each do |cate|
      cate.destroy
    end
    @article=Article.find(params[:article])
    respond_to do |format|
      format.html { redirect_to @article }
      format.js   { render "article_icon/refresh" }
      format.json { render json: @article, status: :created, location: @article }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category=Category.find(params[:id])
    if @category.id.to_int<5
      @categories=Category.find([1,2,3,4])
      @title="SHIVA@GUN"
    else
      @categories=Category.find([5,6,7,8])
      @title="SHIVA@FUN"
    end
    @articles=@category.articles.order("created_at DESC")
  end
end

app/controllers/userinfos_controller.rb
class UserinfosController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tt=1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/like_articles_helper.rb
module LikeArticlesHelper
end

app/helpers/unlike_articles_helper.rb
module UnlikeArticlesHelper
end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article_icon/refresh.js.erb
$(".ar<%= @article.id.to_s %>").replaceWith("<%= j(render @article) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <link rel="icon" href="/assets/site.png">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="http://cdn.bootcss.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/gsap/1.19.0/TweenMax.min.js"></script>
    <script src="http://cdn.bootcss.com/gsap/1.19.0/plugins/ScrollToPlugin.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <%= yield %>
</html>

app/views/shared/_navigator.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to @title, root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav cl-effect-14">
        <% @categories.each do |cate| %>
            <% if cate.id==@category.id %>
                <%= content_tag :li, (link_to cate.name, show_category_path(cate.id)), class: "active" %>
            <% else %>
                <%= content_tag :li, (link_to cate.name, show_category_path(cate.id)) %>
            <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if current_user %>
              <%= link_to current_user.username, "#", class: "dropdown-toggle", data: {toggle: "dropdown"} %>
              <ul class="dropdown-menu" role="menu">
                <%= content_tag :li, (link_to "个人中心", user_detail_path(current_user.id)) %>
                <li><a href="#">我的文章</a></li>
                <li><a href="#">我的收藏</a></li>
                <li class="divider"></li>
                <%= content_tag :li, (link_to "注销", destroy_user_session_path, method: :delete) %>
              </ul>
          <% else %>
              <%= link_to "游客", "#", class: "dropdown-toggle", data: {toggle: "dropdown"} %>
              <ul class="dropdown-menu" role="menu">
                <%= content_tag :li, (link_to "登录", new_user_session_path) %>
                <%= content_tag :li, (link_to "注册", new_user_registration_path) %>
              </ul>
          <% end %>
        </li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
        <button class="button button-glow button-circle button-royal"><i class="fa fa-search"></i></button>
      </form>
    </div><!--/.nav-collapse -->
  </div>
</nav>